POST http://{{host}}/api/todo
Content-Type: application/json

{
    "title": "item",
    "priority": "6"
}

###

GET http://{{host}}/api/todo

###

GET http://{{host}}/api/todo?page=1

###

GET http://{{host}}/api/todo?page=1&limit=20

###

GET http://{{host}}/api/todo?page=1&limit=20&order=a-z

###

GET http://{{host}}/api/todo/6

###

//DELETE http://{{host}}/api/todo/6

###

PUT http://{{host}}/api/todo/8
Content-Type: application/json

[
    {"property": "title", "value": "another item"},
    {"property": "completed", "value": true}
]

###

POST http://{{host}}/api/article
Content-Type: application/json

{
    "title": "article twelve",
    "content": "this is some content"
}

###

GET http://{{host}}/api/article?page=2&limit=5

###

GET http://{{host}}/api/article

###

GET http://{{host}}/

###

POST http://{{host}}/api/product
Content-Type: application/json

{
    "name": "product name",
    "price": 19.99
}

###

GET http://{{host}}/api/product?set=5&limit=10

###

DELETE http://{{host}}/api/todo/9

###


